/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author ASUS
 */
public class SistemaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form SistemaPrincipal
     */
    public SistemaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTrabajossistem = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGenerarVen = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenuItem();
        menuVendedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelTrabajossistemLayout = new javax.swing.GroupLayout(PanelTrabajossistem);
        PanelTrabajossistem.setLayout(PanelTrabajossistemLayout);
        PanelTrabajossistemLayout.setHorizontalGroup(
            PanelTrabajossistemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        PanelTrabajossistemLayout.setVerticalGroup(
            PanelTrabajossistemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        menuAyuda.setText("Ayuda");
        menuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaActionPerformed(evt);
            }
        });
        jMenu1.add(menuAyuda);

        menuSalir.setText("Salir");
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");
        jMenu2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        menuGenerarVen.setText("Generar Venta");
        jMenu2.add(menuGenerarVen);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mantemiento");
        jMenu3.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu3.add(menuCliente);

        menuProductos.setText("Producto");
        jMenu3.add(menuProductos);

        menuVendedor.setText("Vendedor");
        menuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendedorActionPerformed(evt);
            }
        });
        jMenu3.add(menuVendedor);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTrabajossistem)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTrabajossistem)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAyudaActionPerformed

    private void menuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVendedorActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClienteActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane PanelTrabajossistem;
    public static javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    public static javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem menuAyuda;
    public static javax.swing.JMenuItem menuCliente;
    public static javax.swing.JMenuItem menuGenerarVen;
    public static javax.swing.JMenuItem menuProductos;
    public static javax.swing.JMenuItem menuSalir;
    public static javax.swing.JMenuItem menuVendedor;
    // End of variables declaration//GEN-END:variables
}
